services:
  front:
    container_name: cfo-frontend
    build:
      context: ./front
      dockerfile: Dockerfile.production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  back:
    container_name: cfo-backend
    build:
      context: ./back
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
      - MAILER_USERNAME=noreply@crossfitobernai.com
      - MAILER_USERNAME_NAME=Formulaire
      - MAILER_SUBJECT=crossfitobernai@gmail.com
      - ALLOWED_ORIGINS="https://crossfitobernai.com,https://www.crossfitobernai.com,https://crossfitobernai.com:8080"
      - MAILER_PASSWORD
      - MAILER_HOSTNAME
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    container_name: cfo-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.production
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front
      - back
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge
    name: prod_network_cfo