services:
  front:
    container_name: cfo-frontend
    build:
      context: ./front
      dockerfile: Dockerfile.production
    restart: unless-stopped

  back:
    container_name: cfo-backend
    build:
      context: ./back
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped


  nginx:
    container_name: cfo-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.production
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front
      - back
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: prod_network_cfo