FROM node:alpine AS build
WORKDIR '/app'
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:alpine
COPY  --from=build /app/dist /app/dist
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
EXPOSE 80
CMD ["npm", "run", "start:prod"]