FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5174

ARG VITE_REACT_APP_API_URL
ARG VITE_REACT_MODE

ENV VITE_REACT_APP_API_URL=$VITE_REACT_APP_API_URL
ENV VITE_REACT_MODE=$VITE_REACT_MODE

RUN npm run build
CMD ["npm", "run", "dev", "--", "--host"]